### ISSUE TITLE
Generating samples from Azure REST

### ISSUE THREAD

**Issue by zikalino** [puppetlabs/puppetlabs-azure_arm#11]
I just work on similar solution for Ansible at the moment, and I think some features could be reused here as well.
For instance it's possible to pull the sample code from Azure REST API specs.

Here's a directory with 3600 REST API samples generated for Ansible:

https://github.com/zikalino/ansible-hatchery/tree/master/examples.

As you are using REST API directly, it would be very easy to do the same here.

I would be very happy to cooperate.

**Comment by gregohardy** [comment]
Hey Zim. Thanks for the interest and the chat! I'm going to close this as we are going to keep up communications. Thanks!

**Comment by zikalino** [comment]
sure! thanks!
