### ISSUE TITLE
Feature Request: Allow Module To Use Other Environments Besides 'public'

### ISSUE THREAD

**Issue by bryanjbelanger** [puppetlabs/puppetlabs-azure_arm#8]
You need to add an option to change the Azure cloud environment. Currently this only support public.

My work is being done in us government environment. Without this tool I will need to use Terraform to implement.

This is disappointing. I don't like introducing new tools when Puppet is working fine.

**Comment by gregohardy** [comment]
Hi Bryan. Thanks for the suggestion. We are discussing GovCloud at the moment. I'll leave this issue open so I can let you know what the plan is.

**Comment by gregohardy** [comment]
Hi Bryan. We are not going to develop GovCloud at this moment in time. We now autogenerate the azure_arm module and we would need the API spec published to address it. If support is to be done I will let you know.
